
const companies =
[
{label: "MSFT: Microsoft Corporation"},
{label: "AAPL: Apple Inc."},{label: "AMZN: Amazon.com Inc."},{label: "FB: Facebook Inc. Class A"},{label: "GOOGL: Alphabet Inc. Class A"},{label: "GOOG: Alphabet Inc. Class C"},
{label: "JNJ: Johnson & Johnson"},{label: "BRK.B: Berkshire Hathaway Inc. Class B"},{label: "V: Visa Inc. Class A"},{label: "JPM: JPMorgan Chase & Co."},{label: "PG: Procter & Gamble Company"},
{label: "UNH: UnitedHealth Group Incorporated"},{label: "INTC: Intel Corporation"},{label: "HD: Home Depot Inc."},{label: "MA: Mastercard Incorporated Class A"},{label: "VZ: Verizon Communications Inc."},
{label: "T: AT&T Inc."},{label: "NVDA: NVIDIA Corporation"},{label: "DIS: Walt Disney Company"},{label: "PFE: Pfizer Inc."},{label: "MRK: Merck & Co. Inc."},
{label: "CSCO: Cisco Systems Inc."},{label: "BAC: Bank of America Corp"},{label: "XOM: Exxon Mobil Corporation"},{label: "ADBE: Adobe Inc."},{label: "NFLX: Netflix Inc."},
{label: "PEP: PepsiCo Inc."},{label: "PYPL: PayPal Holdings Inc"},{label: "KO: Coca-Cola Company"},{label: "CMCSA: Comcast Corporation Class A"},{label: "WMT: Walmart Inc."},
{label: "CVX: Chevron Corporation"},{label: "ABT: Abbott Laboratories"},{label: "ABBV: AbbVie Inc."},{label: "CRM: salesforce.com inc."},{label: "MCD: McDonald's Corporation"},
{label: "TMO: Thermo Fisher Scientific Inc."},{label: "BMY: Bristol-Myers Squibb Company"},{label: "AMGN: Amgen Inc."},{label: "COST: Costco Wholesale Corporation"},{label: "MDT: Medtronic Plc"},
{label: "LLY: Eli Lilly and Company"},{label: "ACN: Accenture Plc Class A"},{label: "NEE: NextEra Energy Inc."},{label: "NKE: NIKE Inc. Class B"},{label: "UNP: Union Pacific Corporation"},
{label: "ORCL: Oracle Corporation"},{label: "AVGO: Broadcom Inc."},{label: "AMT: American Tower Corporation"},{label: "PM: Philip Morris International Inc."},{label: "TXN: Texas Instruments Incorporated"},
{label: "IBM: International Business Machines Corporation"},{label: "LIN: Linde plc"},{label: "DHR: Danaher Corporation"},{label: "C: Citigroup Inc."},{label: "HON: Honeywell International Inc."},
{label: "WFC: Wells Fargo & Company"},{label: "LOW: Lowe's Companies Inc."},{label: "GILD: Gilead Sciences Inc."},{label: "LMT: Lockheed Martin Corporation"},{label: "RTX: Raytheon Technologies Corporation"},
{label: "QCOM: QUALCOMM Incorporated"},{label: "SBUX: Starbucks Corporation"},{label: "MMM: 3M Company"},{label: "FIS: Fidelity National Information Services Inc."},{label: "CVS: CVS Health Corporation"},
{label: "CHTR: Charter Communications Inc. Class A"},{label: "BLK: BlackRock Inc."},{label: "SPGI: S&P Global Inc."},{label: "BA: Boeing Company"},{label: "INTU: Intuit Inc."},
{label: "MDLZ: Mondelez International Inc. Class A"},{label: "ANTM: Anthem Inc."},{label: "VRTX: Vertex Pharmaceuticals Incorporated"},{label: "CI: Cigna Corporation"},{label: "NOW: ServiceNow Inc."},
{label: "MO: Altria Group Inc"},{label: "BDX: Becton Dickinson and Company"},{label: "CCI: Crown Castle International Corp"},{label: "D: Dominion Energy Inc"},{label: "UPS: United Parcel Service Inc. Class B"},
{label: "BKNG: Booking Holdings Inc."},{label: "PLD: Prologis Inc."},{label: "ISRG: Intuitive Surgical Inc."},{label: "CAT: Caterpillar Inc."},{label: "ZTS: Zoetis Inc. Class A"},
{label: "CME: CME Group Inc. Class A"},{label: "TJX: TJX Companies Inc"},{label: "AXP: American Express Company"},{label: "ADP: Automatic Data Processing Inc."},{label: "SYK: Stryker Corporation"},
{label: "AMD: Advanced Micro Devices Inc."},{label: "GS: Goldman Sachs Group Inc."},{label: "DUK: Duke Energy Corporation"},{label: "TGT: Target Corporation"},{label: "CL: Colgate-Palmolive Company"},
{label: "REGN: Regeneron Pharmaceuticals Inc."},{label: "EQIX: Equinix Inc."},{label: "FISV: Fiserv Inc."},{label: "SO: Southern Company"},{label: "GE: General Electric Company"},
{label: "CSX: CSX Corporation"},{label: "BIIB: Biogen Inc."},{label: "CB: Chubb Limited"},{label: "ATVI: Activision Blizzard Inc."},{label: "HUM: Humana Inc."},
{label: "ICE: Intercontinental Exchange Inc."},{label: "GPN: Global Payments Inc."},{label: "MMC: Marsh & McLennan Companies Inc."},{label: "ILMN: Illumina Inc."},{label: "APD: Air Products and Chemicals Inc."},
{label: "ECL: Ecolab Inc."},{label: "MU: Micron Technology Inc."},{label: "BSX: Boston Scientific Corporation"},{label: "NOC: Northrop Grumman Corporation"},{label: "AMAT: Applied Materials Inc."},
{label: "MS: Morgan Stanley"},{label: "USB: U.S. Bancorp"},{label: "ITW: Illinois Tool Works Inc."},{label: "PNC: PNC Financial Services Group Inc."},{label: "TFC: Truist Financial Corporation"},
{label: "DG: Dollar General Corporation"},{label: "SHW: Sherwin-Williams Company"},{label: "KMB: Kimberly-Clark Corporation"},{label: "DE: Deere & Company"},{label: "NEM: Newmont Corporation"},
{label: "EW: Edwards Lifesciences Corporation"},{label: "NSC: Norfolk Southern Corporation"},{label: "COP: ConocoPhillips"},{label: "ADSK: Autodesk Inc."},{label: "AON: Aon Plc Class A"},
{label: "BAX: Baxter International Inc."},{label: "PGR: Progressive Corporation"},{label: "LHX: L3Harris Technologies Inc"},{label: "EL: Estee Lauder Companies Inc. Class A"},{label: "MCO: Moody's Corporation"},
{label: "AEP: American Electric Power Company Inc."},{label: "WM: Waste Management Inc."},{label: "ADI: Analog Devices Inc."},{label: "SCHW: Charles Schwab Corporation"},{label: "ROP: Roper Technologies Inc."},
{label: "LRCX: Lam Research Corporation"},{label: "CNC: Centene Corporation"},{label: "GIS: General Mills Inc."},{label: "TMUS: T-Mobile US Inc."},{label: "DLR: Digital Realty Trust Inc."},
{label: "DD: DuPont de Nemours Inc."},{label: "EXC: Exelon Corporation"},{label: "EMR: Emerson Electric Co."},{label: "EA: Electronic Arts Inc."},{label: "SRE: Sempra Energy"},
{label: "SBAC: SBA Communications Corp. Class A"},{label: "ETN: Eaton Corp. Plc"},{label: "ROST: Ross Stores Inc."},{label: "EBAY: eBay Inc."},{label: "PSX: Phillips 66"},
{label: "DXCM: DexCom Inc."},{label: "GD: General Dynamics Corporation"},{label: "XEL: Xcel Energy Inc."},{label: "GM: General Motors Company"},{label: "WBA: Walgreens Boots Alliance Inc"},
{label: "ALL: Allstate Corporation"},{label: "COF: Capital One Financial Corporation"},{label: "ORLY: O'Reilly Automotive Inc."},{label: "FDX: FedEx Corporation"},{label: "BK: Bank of New York Mellon Corporation"},
{label: "KMI: Kinder Morgan Inc Class P"},{label: "PSA: Public Storage"},{label: "EOG: EOG Resources Inc."},{label: "CTSH: Cognizant Technology Solutions Corporation Class A"},{label: "STZ: Constellation Brands Inc. Class A"},
{label: "WEC: WEC Energy Group Inc"},{label: "APH: Amphenol Corporation Class A"},{label: "DOW: Dow Inc."},{label: "TROW: T. Rowe Price Group"},{label: "HCA: HCA Healthcare Inc"},
{label: "VRSK: Verisk Analytics Inc"},{label: "MET: MetLife Inc."},{label: "SYY: Sysco Corporation"},{label: "MSCI: MSCI Inc. Class A"},{label: "INFO: IHS Markit Ltd."},
{label: "KLAC: KLA Corporation"},{label: "TRV: Travelers Companies Inc."},{label: "MNST: Monster Beverage Corporation"},{label: "AZO: AutoZone Inc."},{label: "VLO: Valero Energy Corporation"},
{label: "A: Agilent Technologies Inc."},{label: "TEL: TE Connectivity Ltd."},{label: "YUM: Yum! Brands Inc."},{label: "ES: Eversource Energy"},{label: "IQV: IQVIA Holdings Inc"},
{label: "SNPS: Synopsys Inc."},{label: "AFL: Aflac Incorporated"},{label: "ALXN: Alexion Pharmaceuticals Inc."},{label: "IDXX: IDEXX Laboratories Inc."},{label: "AIG: American International Group Inc."},
{label: "KR: Kroger Co."},{label: "WLTW: Willis Towers Watson Public Limited Company"},{label: "ZBH: Zimmer Biomet Holdings Inc."},{label: "CMI: Cummins Inc."},{label: "CLX: Clorox Company"},
{label: "PEG: Public Service Enterprise Group Inc"},{label: "CDNS: Cadence Design Systems Inc."},{label: "CMG: Chipotle Mexican Grill Inc."},{label: "MCK: McKesson Corporation"},{label: "SLB: Schlumberger NV"},
{label: "PCAR: PACCAR Inc"},{label: "ED: Consolidated Edison Inc."},{label: "ROK: Rockwell Automation Inc."},{label: "WMB: Williams Companies Inc."},{label: "PRU: Prudential Financial Inc."},
{label: "JCI: Johnson Controls International plc"},{label: "ANSS: ANSYS Inc."},{label: "PPG: PPG Industries Inc."},{label: "MAR: Marriott International Inc. Class A"},{label: "TWTR: Twitter Inc."},
{label: "FAST: Fastenal Company"},{label: "BLL: Ball Corporation"},{label: "DLTR: Dollar Tree Inc."},{label: "MSI: Motorola Solutions Inc."},{label: "XLNX: Xilinx Inc."},
{label: "PH: Parker-Hannifin Corporation"},{label: "PAYX: Paychex Inc."},{label: "CERN: Cerner Corporation"},{label: "RMD: ResMed Inc."},{label: "MCHP: Microchip Technology Incorporated"},
{label: "AWK: American Water Works Company Inc."},{label: "FE: FirstEnergy Corp."},{label: "MPC: Marathon Petroleum Corporation"},{label: "VRSN: VeriSign Inc."},{label: "HPQ: HP Inc."},
{label: "HLT: Hilton Worldwide Holdings Inc"},{label: "F: Ford Motor Company"},{label: "STT: State Street Corporation"},{label: "ADM: Archer-Daniels-Midland Company"},{label: "AVB: AvalonBay Communities Inc."},
{label: "TT: Trane Technologies plc"},{label: "PPL: PPL Corporation"},{label: "MKC: McCormick & Company Incorporated"},{label: "OTIS: Otis Worldwide Corporation"},{label: "EQR: Equity Residential"},
{label: "TDG: TransDigm Group Incorporated"},{label: "FLT: FleetCor Technologies Inc."},{label: "EIX: Edison International"},{label: "AME: AMETEK Inc."},{label: "DTE: DTE Energy Company"},
{label: "CTAS: Cintas Corporation"},{label: "WELL: Welltower Inc."},{label: "CTVA: Corteva Inc"},{label: "ETR: Entergy Corporation"},{label: "SWKS: Skyworks Solutions Inc."},
{label: "KEYS: Keysight Technologies Inc"},{label: "HSY: Hershey Company"},{label: "FTNT: Fortinet Inc."},{label: "MTD: Mettler-Toledo International Inc."},{label: "APTV: Aptiv PLC"},
{label: "MKTX: MarketAxess Holdings Inc."},{label: "O: Realty Income Corporation"},{label: "SWK: Stanley Black & Decker Inc."},{label: "KHC: Kraft Heinz Company"},{label: "ARE: Alexandria Real Estate Equities Inc."},
{label: "DHI: D.R. Horton Inc."},{label: "EFX: Equifax Inc."},{label: "VFC: V.F. Corporation"},{label: "CHD: Church & Dwight Co. Inc."},{label: "CPRT: Copart Inc."},
{label: "FRC: First Republic Bank"},{label: "AEE: Ameren Corporation"},{label: "TSN: Tyson Foods Inc. Class A"},{label: "INCY: Incyte Corporation"},{label: "RSG: Republic Services Inc."},
{label: "FTV: Fortive Corp."},{label: "BBY: Best Buy Co. Inc."},{label: "AMP: Ameriprise Financial Inc."},{label: "SPG: Simon Property Group Inc."},{label: "ALGN: Align Technology Inc."},
{label: "GLW: Corning Inc"},{label: "AJG: Arthur J. Gallagher & Co."},{label: "AKAM: Akamai Technologies Inc."},{label: "CTXS: Citrix Systems Inc."},{label: "LH: Laboratory Corporation of America Holdings"},
{label: "LEN: Lennar Corporation Class A"},{label: "LUV: Southwest Airlines Co."},{label: "CAG: Conagra Brands Inc."},{label: "NTRS: Northern Trust Corporation"},{label: "TFX: Teleflex Incorporated"},
{label: "CARR: Carrier Global Corp."},{label: "CMS: CMS Energy Corporation"},{label: "AMCR: Amcor PLC"},{label: "LYB: LyondellBasell Industries NV"},{label: "ODFL: Old Dominion Freight Line Inc."},
{label: "K: Kellogg Company"},{label: "LVS: Las Vegas Sands Corp."},{label: "CAH: Cardinal Health Inc."},{label: "WST: West Pharmaceutical Services Inc."},{label: "CDW: CDW Corp."},
{label: "ESS: Essex Property Trust Inc."},{label: "DGX: Quest Diagnostics Incorporated"},{label: "MXIM: Maxim Integrated Products Inc."},{label: "COO: Cooper Companies Inc."},{label: "TTWO: Take-Two Interactive Software Inc."},
{label: "PXD: Pioneer Natural Resources Company"},{label: "OKE: ONEOK Inc."},{label: "DPZ: Domino's Pizza Inc."},{label: "WY: Weyerhaeuser Company"},{label: "KSU: Kansas City Southern"},
{label: "DFS: Discover Financial Services"},{label: "CBRE: CBRE Group Inc. Class A"},{label: "PAYC: Paycom Software Inc."},{label: "DAL: Delta Air Lines Inc."},{label: "KMX: CarMax Inc."},
{label: "TSCO: Tractor Supply Company"},{label: "ABC: AmerisourceBergen Corporation"},{label: "VMC: Vulcan Materials Company"},{label: "IFF: International Flavors & Fragrances Inc."},{label: "HOLX: Hologic Inc."},
{label: "ZBRA: Zebra Technologies Corporation Class A"},{label: "DOV: Dover Corporation"},{label: "STE: STERIS Plc"},{label: "EVRG: Evergy Inc."},{label: "LDOS: Leidos Holdings Inc."},
{label: "ULTA: Ulta Beauty Inc"},{label: "MTB: M&T Bank Corporation"},{label: "BR: Broadridge Financial Solutions Inc."},{label: "HIG: Hartford Financial Services Group Inc."},{label: "FITB: Fifth Third Bancorp"},
{label: "JKHY: Jack Henry & Associates Inc."},{label: "TIF: Tiffany & Co."},{label: "NDAQ: Nasdaq Inc."},{label: "HRL: Hormel Foods Corporation"},{label: "GWW: W.W. Grainger Inc."},
{label: "IP: International Paper Company"},{label: "MAS: Masco Corporation"},{label: "MAA: Mid-America Apartment Communities Inc."},{label: "FCX: Freeport-McMoRan Inc."},{label: "GRMN: Garmin Ltd."},
{label: "WDC: Western Digital Corporation"},{label: "EXPD: Expeditors International of Washington Inc."},{label: "NLOK: NortonLifeLock Inc."},{label: "SJM: J.M. Smucker Company"},{label: "VTR: Ventas Inc."},
{label: "WAT: Waters Corporation"},{label: "NUE: Nucor Corporation"},{label: "FMC: FMC Corporation"},{label: "ANET: Arista Networks Inc."},{label: "DRE: Duke Realty Corporation"},
{label: "HPE: Hewlett Packard Enterprise Co."},{label: "EXR: Extra Space Storage Inc."},{label: "BXP: Boston Properties Inc."},{label: "ATO: Atmos Energy Corporation"},{label: "HES: Hess Corporation"},
{label: "STX: Seagate Technology PLC"},{label: "QRVO: Qorvo Inc."},{label: "GPC: Genuine Parts Company"},{label: "PEAK: Healthpeak Properties Inc."},{label: "BF.B: Brown-Forman Corporation Class B"},
{label: "MLM: Martin Marietta Materials Inc."},{label: "OMC: Omnicom Group Inc"},{label: "IEX: IDEX Corporation"},{label: "LNT: Alliant Energy Corp"},{label: "XYL: Xylem Inc."},
{label: "CBOE: Cboe Global Markets Inc"},{label: "KEY: KeyCorp"},{label: "OXY: Occidental Petroleum Corporation"},{label: "SYF: Synchrony Financial"},{label: "J: Jacobs Engineering Group Inc."},
{label: "NVR: NVR Inc."},{label: "VIAC: ViacomCBS Inc. Class B"},{label: "WAB: Westinghouse Air Brake Technologies Corporation"},{label: "SIVB: SVB Financial Group"},{label: "PKI: PerkinElmer Inc."},
{label: "VAR: Varian Medical Systems Inc."},{label: "EXPE: Expedia Group Inc."},{label: "CHRW: C.H. Robinson Worldwide Inc."},{label: "RF: Regions Financial Corporation"},{label: "CXO: Concho Resources Inc."},
{label: "CE: Celanese Corporation"},{label: "UDR: UDR Inc."},{label: "IT: Gartner Inc."},{label: "BKR: Baker Hughes Company Class A"},{label: "CFG: Citizens Financial Group Inc."},
{label: "URI: United Rentals Inc."},{label: "HAL: Halliburton Company"},{label: "XRAY: DENTSPLY SIRONA Inc."},{label: "ETFC: E*TRADE Financial Corporation"},{label: "FOXA: Fox Corporation Class A"},
{label: "JBHT: J.B. Hunt Transport Services Inc."},{label: "NTAP: NetApp Inc."},{label: "ABMD: ABIOMED Inc."},{label: "PFG: Principal Financial Group Inc."},{label: "IR: Ingersoll Rand Inc."},
{label: "AAP: Advance Auto Parts Inc."},{label: "PKG: Packaging Corporation of America"},{label: "CTL: CenturyLink Inc."},{label: "HAS: Hasbro Inc."},{label: "DRI: Darden Restaurants Inc."},
{label: "ALLE: Allegion PLC"},{label: "EMN: Eastman Chemical Company"},{label: "AVY: Avery Dennison Corporation"},{label: "HBAN: Huntington Bancshares Incorporated"},{label: "NRG: NRG Energy Inc."},
{label: "CINF: Cincinnati Financial Corporation"},{label: "HSIC: Henry Schein Inc."},{label: "CNP: CenterPoint Energy Inc."},{label: "RCL: Royal Caribbean Cruises Ltd."},{label: "MGM: MGM Resorts International"},
{label: "NI: NiSource Inc"},{label: "MYL: Mylan N.V."},{label: "LW: Lamb Weston Holdings Inc."},{label: "PNW: Pinnacle West Capital Corporation"},{label: "FFIV: F5 Networks Inc."},
{label: "PHM: PulteGroup Inc."},{label: "CPB: Campbell Soup Company"},{label: "HST: Host Hotels & Resorts Inc."},{label: "RJF: Raymond James Financial Inc."},{label: "FBHS: Fortune Brands Home & Security Inc."},
{label: "L: Loews Corporation"},{label: "LKQ: LKQ Corporation"},{label: "UHS: Universal Health Services Inc. Class B"},{label: "WRB: W. R. Berkley Corporation"},{label: "WU: Western Union Company"},
{label: "AES: AES Corporation"},{label: "HII: Huntington Ingalls Industries Inc."},{label: "ALB: Albemarle Corporation"},{label: "JNPR: Juniper Networks Inc."},{label: "COG: Cabot Oil & Gas Corporation"},
{label: "DISH: DISH Network Corporation Class A"},{label: "WYNN: Wynn Resorts Limited"},{label: "RE: Everest Re Group Ltd."},{label: "GL: Globe Life Inc."},{label: "WHR: Whirlpool Corporation"},
{label: "LNC: Lincoln National Corporation"},{label: "PRGO: Perrigo Co. Plc"},{label: "IRM: Iron Mountain Inc."},{label: "DVA: DaVita Inc."},{label: "WRK: WestRock Company"},
{label: "REG: Regency Centers Corporation"},{label: "TXT: Textron Inc."},{label: "SNA: Snap-on Incorporated"},{label: "TAP: Molson Coors Beverage Company Class B"},{label: "LYV: Live Nation Entertainment Inc."},
{label: "FANG: Diamondback Energy Inc."},{label: "BWA: BorgWarner Inc."},{label: "IPG: Interpublic Group of Companies Inc."},{label: "DISCK: Discovery Inc. Class C"},{label: "PNR: Pentair plc"},
{label: "AOS: A. O. Smith Corporation"},{label: "CF: CF Industries Holdings Inc."},{label: "AIZ: Assurant Inc."},{label: "CCL: Carnival Corporation"},{label: "FLIR: FLIR Systems Inc."},
{label: "UAL: United Airlines Holdings Inc."},{label: "RHI: Robert Half International Inc."},{label: "ROL: Rollins Inc."},{label: "VNO: Vornado Realty Trust"},{label: "ZION: Zions Bancorporation N.A."},
{label: "MHK: Mohawk Industries Inc."},{label: "FRT: Federal Realty Investment Trust"},{label: "IPGP: IPG Photonics Corporation"},{label: "AIV: Apartment Investment & Management Co Class A"},{label: "BEN: Franklin Resources Inc."},
{label: "PWR: Quanta Services Inc."},{label: "CMA: Comerica Incorporated"},{label: "PBCT: People's United Financial Inc."},{label: "HWM: Howmet Aerospace Inc."},{label: "SEE: Sealed Air Corporation"},
{label: "NWL: Newell Brands Inc"},{label: "NLSN: Nielsen Holdings Plc"},{label: "NOV: National Oilwell Varco Inc."},{label: "HFC: HollyFrontier Corporation"},{label: "KIM: Kimco Realty Corporation"},
{label: "FOX: Fox Corporation Class B"},{label: "NWSA: News Corporation Class A"},{label: "MRO: Marathon Oil Corporation"},{label: "MOS: Mosaic Company"},{label: "ALK: Alaska Air Group Inc."},
{label: "NBL: Noble Energy Inc."},{label: "DVN: Devon Energy Corporation"},{label: "AAL: American Airlines Group Inc."},{label: "APA: Apache Corporation"},{label: "LEG: Leggett & Platt Incorporated"},
{label: "RL: Ralph Lauren Corporation Class A"},{label: "TPR: Tapestry Inc."},{label: "DXC: DXC Technology Co."},{label: "LB: L Brands Inc."},{label: "HBI: Hanesbrands Inc."},
{label: "SLG: SL Green Realty Corp."},{label: "DISCA: Discovery Inc. Class A"},{label: "NCLH: Norwegian Cruise Line Holdings Ltd."},{label: "PVH: PVH Corp."},{label: "FLS: Flowserve Corporation"},
{label: "HRB: H&R Block Inc."},{label: "HOG: Harley-Davidson Inc."},{label: "UNM: Unum Group"},{label: "FTI: TechnipFMC Plc"},{label: "KSS: Kohl's Corporation"},
{label: "IVZ: Invesco Ltd."},{label: "XRX: Xerox Holdings Corporation"},{label: "GPS: Gap Inc."},{label: "ADS: Alliance Data Systems Corporation"},{label: "JWN: Nordstrom Inc."},
{label: "UAA: Under Armour Inc. Class A"},{label: "UA: Under Armour Inc. Class C"},{label: "NWS: News Corporation Class B"},{label: "COTY: Coty Inc. Class A"},
]

export {companies};